/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SharedWithMeRouteImport } from './routes/shared-with-me'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as FilesFolderIdRouteImport } from './routes/files.$folderId'
import { Route as SharedNodeIdRouteImport } from './routes/shared.$nodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedWithMeRoute = SharedWithMeRouteImport.update({
  id: '/shared-with-me',
  path: '/shared-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesFolderIdRoute = FilesFolderIdRouteImport.update({
  id: '/files/$folderId',
  path: '/files/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedNodeIdRoute = SharedNodeIdRouteImport.update({
  id: '/shared/$nodeId',
  path: '/shared/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/trash': typeof TrashRoute
  '/files/$folderId': typeof FilesFolderIdRoute
  '/shared/$nodeId': typeof SharedNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/trash': typeof TrashRoute
  '/files/$folderId': typeof FilesFolderIdRoute
  '/shared/$nodeId': typeof SharedNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/recent': typeof RecentRoute
  '/settings': typeof SettingsRoute
  '/shared-with-me': typeof SharedWithMeRoute
  '/trash': typeof TrashRoute
  '/files/$folderId': typeof FilesFolderIdRoute
  '/shared/$nodeId': typeof SharedNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/favorites'
    | '/help'
    | '/onboarding'
    | '/recent'
    | '/settings'
    | '/shared-with-me'
    | '/trash'
    | '/files/$folderId'
    | '/shared/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/favorites'
    | '/help'
    | '/onboarding'
    | '/recent'
    | '/settings'
    | '/shared-with-me'
    | '/trash'
    | '/files/$folderId'
    | '/shared/$nodeId'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/favorites'
    | '/help'
    | '/onboarding'
    | '/recent'
    | '/settings'
    | '/shared-with-me'
    | '/trash'
    | '/files/$folderId'
    | '/shared/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  RecentRoute: typeof RecentRoute
  SettingsRoute: typeof SettingsRoute
  SharedWithMeRoute: typeof SharedWithMeRoute
  TrashRoute: typeof TrashRoute
  FilesFolderIdRoute: typeof FilesFolderIdRoute
  SharedNodeIdRoute: typeof SharedNodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-with-me': {
      id: '/shared-with-me'
      path: '/shared-with-me'
      fullPath: '/shared-with-me'
      preLoaderRoute: typeof SharedWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$folderId': {
      id: '/files/$folderId'
      path: '/files/$folderId'
      fullPath: '/files/$folderId'
      preLoaderRoute: typeof FilesFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$nodeId': {
      id: '/shared/$nodeId'
      path: '/shared/$nodeId'
      fullPath: '/shared/$nodeId'
      preLoaderRoute: typeof SharedNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  RecentRoute: RecentRoute,
  SettingsRoute: SettingsRoute,
  SharedWithMeRoute: SharedWithMeRoute,
  TrashRoute: TrashRoute,
  FilesFolderIdRoute: FilesFolderIdRoute,
  SharedNodeIdRoute: SharedNodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
